// AUTO-GENERATED from Stretch_Desk_Comprehensive_Rehab_Library_v2.xlsx
// Do NOT edit by hand. Regenerate with: python3 scripts/build-library.py

export type ClinicalArea =
  | "Cervical Flexor/Extensor Complex"
  | "Axioscapular Group"
  | "Scapulohumeral / Rotator Cuff Complex"
  | "Pectoral / Anterior Shoulder Complex"
  | "Thoracic Spine / Rib Cage Complex"
  | "Lumbopelvic Core Stabiliser Complex"
  | "Lumbar Extensor / Quadratus Lumborum Complex"
  | "Hip Flexor Complex"
  | "Gluteal / Deep Hip Rotator Complex"
  | "Hamstring / Posterior Thigh Complex"
  | "Hip Abductor / Adductor Complex"
  | "Forearm / Wrist / Hand Complex"
  | "Calf / Ankle / Foot Complex";

export type SkillLevel = "beginner" | "intermediate" | "advanced" | "pro";
export type Context = "Seated" | "Standing" | "Seated or standing";

export interface LibraryItem {
  area: ClinicalArea;
  primaryMuscle: string;
  otherMuscles: string[];
  name: string;
  durationSeconds: number;
  repetitions: number;
  skillLevel: SkillLevel;
  context: Context;
  needsEquipment: boolean;
  equipment: string | null;
}

// User-facing simplified body areas. Each maps to one or more clinical complexes.
export type UserBodyArea =
  | "neck"
  | "shoulders"
  | "chest"
  | "back"
  | "hips"
  | "legs"
  | "arms";

export const USER_AREA_TO_CLINICAL: Record<UserBodyArea, ClinicalArea[]> = {
  neck: ["Cervical Flexor/Extensor Complex"],
  shoulders: [
    "Axioscapular Group",
    "Scapulohumeral / Rotator Cuff Complex",
  ],
  chest: ["Pectoral / Anterior Shoulder Complex"],
  back: [
    "Thoracic Spine / Rib Cage Complex",
    "Lumbar Extensor / Quadratus Lumborum Complex",
    "Lumbopelvic Core Stabiliser Complex",
  ],
  hips: [
    "Hip Flexor Complex",
    "Gluteal / Deep Hip Rotator Complex",
    "Hip Abductor / Adductor Complex",
  ],
  legs: [
    "Hamstring / Posterior Thigh Complex",
    "Calf / Ankle / Foot Complex",
  ],
  arms: ["Forearm / Wrist / Hand Complex"],
};

export const USER_AREA_LABELS: Record<UserBodyArea, string> = {
  neck: "Neck",
  shoulders: "Shoulders",
  chest: "Chest",
  back: "Back",
  hips: "Hips",
  legs: "Legs",
  arms: "Arms",
};

export const STRETCH_LIBRARY: LibraryItem[] = [
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "deep neck flexors",
    otherMuscles: ["suboccipitals", "cervical extensors"],
    name: "Chin Tuck Mobility Hold",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "cervical extensors",
    otherMuscles: ["upper trapezius", "suboccipitals"],
    name: "Seated Neck Flexion Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "anterior neck tissues",
    otherMuscles: ["sternocleidomastoid", "scalenes"],
    name: "Seated Neck Extension Opener",
    durationSeconds: 20,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "suboccipitals",
    otherMuscles: ["deep cervical extensors"],
    name: "Upper Cervical Nod Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "sternocleidomastoid",
    otherMuscles: ["scalenes", "anterior neck"],
    name: "Sternocleidomastoid Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Seated or standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "scalenes",
    otherMuscles: ["sternocleidomastoid", "upper trapezius"],
    name: "Scalene Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "cervical mobility system",
    otherMuscles: ["deep neck stabilisers"],
    name: "Neck CARs Slow Circle",
    durationSeconds: 45,
    repetitions: 3,
    skillLevel: "intermediate",
    context: "Seated or standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "upper cervical extensors",
    otherMuscles: ["suboccipitals", "deep neck flexors"],
    name: "Towel Assisted Cervical Extension",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Seated",
    needsEquipment: true,
    equipment: "Small towel",
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "deep neck flexors",
    otherMuscles: ["cervical extensors"],
    name: "Wall Chin Tuck with Occipital Glide",
    durationSeconds: 30,
    repetitions: 3,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "suboccipitals",
    otherMuscles: ["upper cervical fascia"],
    name: "Supine Suboccipital Release Breathing",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: true,
    equipment: "Tennis ball or towel",
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "upper trapezius",
    otherMuscles: ["levator scapulae", "scalenes"],
    name: "Upper Trapezius Side Bend Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "levator scapulae",
    otherMuscles: ["upper trapezius", "cervical extensors"],
    name: "Levator Scapulae Pocket Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "rhomboids",
    otherMuscles: ["middle trapezius"],
    name: "Seated Scapular Protraction Reach",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "rhomboids",
    otherMuscles: ["posterior shoulder", "thoracic spine"],
    name: "Thread the Needle Desk Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "serratus anterior",
    otherMuscles: ["latissimus dorsi", "intercostals"],
    name: "Doorframe Serratus Lat Reach",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "lower trapezius",
    otherMuscles: ["latissimus dorsi", "thoracic fascia"],
    name: "Child Pose Side Reach Desk Version",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "upper/lower trapezius",
    otherMuscles: ["levator scapulae"],
    name: "Scapular Elevation Depression Mobility",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated or standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "rhomboids",
    otherMuscles: ["trapezius", "posterior shoulder"],
    name: "Band Assisted Scapular Distraction",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "lower trapezius",
    otherMuscles: ["pecs", "rotator cuff"],
    name: "Wall Angels Mobility Stretch",
    durationSeconds: 60,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "serratus anterior",
    otherMuscles: ["rhomboids", "trapezius"],
    name: "Quadruped Scapular Rock Back",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "posterior deltoid",
    otherMuscles: ["infraspinatus", "teres minor"],
    name: "Cross Body Posterior Shoulder Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated or standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "posterior capsule",
    otherMuscles: ["infraspinatus", "teres minor"],
    name: "Sleeper Stretch Modified",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "subscapularis",
    otherMuscles: ["pectorals", "anterior capsule"],
    name: "Doorway External Rotation Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "external rotators",
    otherMuscles: ["posterior shoulder"],
    name: "Behind Back Internal Rotation Towel Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Small towel",
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "latissimus dorsi",
    otherMuscles: ["teres major", "triceps long head"],
    name: "Wall Shoulder Flexion Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "latissimus dorsi",
    otherMuscles: ["rotator cuff", "thoracic spine"],
    name: "Desk Shoulder Flexion Prayer Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "glenohumeral mobility system",
    otherMuscles: ["rotator cuff"],
    name: "Shoulder CARs Slow Rotation",
    durationSeconds: 60,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "latissimus dorsi",
    otherMuscles: ["teres major", "triceps"],
    name: "Band Assisted Shoulder Flexion Opener",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "posterior shoulder capsule",
    otherMuscles: ["posterior deltoid", "rotator cuff"],
    name: "Posterior Capsule Wall Lean",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "anterior shoulder",
    otherMuscles: ["pectoralis minor", "biceps tendon region"],
    name: "Desk Pec-to-Shoulder Opener",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis major",
    otherMuscles: ["anterior deltoid"],
    name: "Doorway Pec Major Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis major",
    otherMuscles: ["pectoralis minor", "anterior deltoid"],
    name: "Corner Chest Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis minor",
    otherMuscles: ["anterior shoulder"],
    name: "Low Doorway Pec Minor Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis major",
    otherMuscles: ["anterior deltoid", "biceps"],
    name: "Seated Hands Behind Back Chest Opener",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis major",
    otherMuscles: ["anterior shoulder", "biceps"],
    name: "Desk Edge Chest Opener",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "biceps long head",
    otherMuscles: ["pec major", "anterior deltoid"],
    name: "Wall Biceps and Chest Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis minor",
    otherMuscles: ["pec major", "thoracic spine"],
    name: "Foam Roller Chest Opener",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Foam roller",
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "anterior shoulder",
    otherMuscles: ["pectorals", "thoracic extensors"],
    name: "Standing W-to-Y Chest Opener",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis major/minor",
    otherMuscles: ["shoulder capsule", "thoracic spine"],
    name: "Supine Snow Angel Mobility",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis major upper fibres",
    otherMuscles: ["latissimus dorsi", "anterior shoulder"],
    name: "Doorframe Overhead Pec Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic rotators",
    otherMuscles: ["intercostals", "rhomboids"],
    name: "Seated Thoracic Rotation",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic spine",
    otherMuscles: ["pecs", "intercostals"],
    name: "Open Book Rotation",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic extensors",
    otherMuscles: ["latissimus dorsi", "shoulders"],
    name: "Desk Thoracic Extension",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic extensors",
    otherMuscles: ["rib cage"],
    name: "Chair Back Extension Mobilisation",
    durationSeconds: 30,
    repetitions: 3,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic rotators",
    otherMuscles: ["rhomboids", "posterior shoulder"],
    name: "Quadruped Thread the Needle",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic rotation",
    otherMuscles: ["shoulder mobility", "rib cage"],
    name: "Standing Wall Windmill",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "intercostals",
    otherMuscles: ["latissimus dorsi", "quadratus lumborum"],
    name: "Side Bend Rib Opener",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated or standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "intercostals",
    otherMuscles: ["diaphragm", "thoracic fascia"],
    name: "Breathing Expansion Rib Stretch",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic extensors",
    otherMuscles: ["rib cage", "lats"],
    name: "Foam Roller Thoracic Extension",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Foam roller",
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic spine",
    otherMuscles: ["hip flexors", "obliques"],
    name: "Half Kneeling Thoracic Rotation Reach",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "lumbopelvic fascia",
    otherMuscles: ["abdominals", "lumbar extensors"],
    name: "Seated Posterior Pelvic Tilt Mobility",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "deep core mobility system",
    otherMuscles: ["hip flexors", "lumbar extensors"],
    name: "Seated Anterior Pelvic Tilt Mobility",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "lumbar mobility system",
    otherMuscles: ["thoracic spine", "pelvis"],
    name: "Standing Cat Cow at Desk",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "lumbar extensors",
    otherMuscles: ["glutes", "thoracolumbar fascia"],
    name: "Supine Knees-to-Chest",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "obliques",
    otherMuscles: ["quadratus lumborum", "lumbar fascia"],
    name: "Supine Lumbar Rotation",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "obliques",
    otherMuscles: ["quadratus lumborum", "intercostals"],
    name: "Standing Oblique Side Bend Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "thoracolumbar fascia",
    otherMuscles: ["lats", "lumbar extensors"],
    name: "Child Pose Desk Rock Back",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "diaphragm",
    otherMuscles: ["pelvic floor", "deep core"],
    name: "90-90 Breathing Stretch",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Chair or wall",
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "obliques",
    otherMuscles: ["hip flexors", "lats"],
    name: "Half Kneeling Oblique Reach",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "abdominal fascia",
    otherMuscles: ["lumbar spine", "hip flexors"],
    name: "Prone Press Up Mobility",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "lumbar extensors",
    otherMuscles: ["hamstrings", "thoracolumbar fascia"],
    name: "Seated Forward Fold",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "quadratus lumborum",
    otherMuscles: ["obliques", "intercostals"],
    name: "Seated Side Bend QL Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "quadratus lumborum",
    otherMuscles: ["lats", "obliques"],
    name: "Standing QL Wall Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "quadratus lumborum",
    otherMuscles: ["lats", "lumbar extensors"],
    name: "Child Pose Side Reach",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "lumbar extensors",
    otherMuscles: ["multifidus", "abdominals"],
    name: "Cat Cow Lumbar Mobility",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "gluteals",
    otherMuscles: ["QL", "lumbar fascia"],
    name: "Supine Knee-to-Opposite-Shoulder",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "abdominal fascia",
    otherMuscles: ["hip flexors", "lumbar spine"],
    name: "Standing Backbend Counter Stretch",
    durationSeconds: 20,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "lumbar extensors",
    otherMuscles: ["thoracolumbar fascia"],
    name: "Desk Supported Lumbar Decompression",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "thoracolumbar junction",
    otherMuscles: ["QL", "thoracic spine"],
    name: "Open Book with Lumbar Lock",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "quadratus lumborum",
    otherMuscles: ["lumbar fascia"],
    name: "Foam Roller QL Release",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Foam roller or ball",
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "iliopsoas",
    otherMuscles: ["rectus femoris"],
    name: "Standing Hip Flexor Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "iliopsoas",
    otherMuscles: ["rectus femoris", "TFL"],
    name: "Half Kneeling Hip Flexor Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "rectus femoris",
    otherMuscles: ["iliopsoas", "anterior hip capsule"],
    name: "Couch Stretch",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Chair or wall",
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "iliopsoas",
    otherMuscles: ["TFL", "rectus femoris"],
    name: "Desk Supported Hip Extension Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "iliopsoas",
    otherMuscles: ["rectus femoris", "glute max"],
    name: "Lunge with Posterior Pelvic Tilt",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "rectus femoris",
    otherMuscles: ["quadriceps", "hip flexors"],
    name: "Standing Quad Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "rectus femoris",
    otherMuscles: ["hip flexors"],
    name: "Side Lying Quad Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "tensor fascia latae",
    otherMuscles: ["hip flexors", "lateral hip"],
    name: "TFL Wall Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "iliopsoas",
    otherMuscles: ["deep core", "glutes"],
    name: "Psoas March Mobility Hold",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band optional",
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "rectus femoris",
    otherMuscles: ["iliopsoas", "anterior hip"],
    name: "Rear Foot Elevated Hip Flexor Stretch",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Chair or bench",
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "piriformis",
    otherMuscles: ["glute maximus", "deep hip rotators"],
    name: "Seated Figure Four Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "piriformis",
    otherMuscles: ["glute medius/minimus"],
    name: "Supine Figure Four Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "deep hip rotators",
    otherMuscles: ["glutes"],
    name: "Seated Hip External Rotation Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "gluteus maximus",
    otherMuscles: ["piriformis", "hip rotators"],
    name: "Pigeon Pose Modified",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "hip rotators",
    otherMuscles: ["glutes", "adductors"],
    name: "90-90 Hip Switch Stretch",
    durationSeconds: 60,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "gluteus maximus",
    otherMuscles: ["lumbar fascia"],
    name: "Supine Knee-to-Chest Glute Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "piriformis",
    otherMuscles: ["glute max", "deep rotators"],
    name: "Standing Figure Four Desk Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "gluteals",
    otherMuscles: ["hip flexors", "thoracic spine"],
    name: "Pretzel Stretch",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "piriformis",
    otherMuscles: ["sciatic interface", "hamstrings"],
    name: "Seated Piriformis Nerve-Safe Glide",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "glute medius",
    otherMuscles: ["adductors", "hip capsule"],
    name: "Frog Rock Back Hip Opener",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["calves"],
    name: "Seated Hamstring Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["calves", "glutes"],
    name: "Standing Hamstring Stretch on Desk",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["calves", "sciatic nerve interface"],
    name: "Supine Hamstring Strap Stretch",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: true,
    equipment: "Strap or towel",
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["calves"],
    name: "Dynamic Hamstring Sweeps",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["glutes", "calves"],
    name: "Single Leg Romanian Deadlift Reach Mobility",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["calves", "glutes"],
    name: "Half Split Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "neural interface",
    otherMuscles: ["hamstrings", "calves"],
    name: "Sciatic Nerve Slider",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["calves"],
    name: "Wall Hamstring Stretch",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Wall",
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "posterior chain",
    otherMuscles: ["hamstrings", "spinal extensors"],
    name: "Jefferson Curl Mobility Light",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Light weight optional",
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["calves", "sciatic interface"],
    name: "Banded Hamstring Floss",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "adductors",
    otherMuscles: ["hamstrings", "glutes"],
    name: "Standing Adductor Side Lunge Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "adductors",
    otherMuscles: ["hip rotators"],
    name: "Seated Butterfly Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "adductors",
    otherMuscles: ["glutes", "hip capsule"],
    name: "Frog Stretch",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "TFL",
    otherMuscles: ["glute medius", "lateral hip"],
    name: "Standing ITB/TFL Cross-Over Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "adductors",
    otherMuscles: ["hamstrings", "ankles"],
    name: "Cossack Squat Mobility Hold",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "hip internal rotators",
    otherMuscles: ["adductors", "glute medius"],
    name: "90-90 Hip Internal Rotation Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "adductors",
    otherMuscles: ["hamstrings", "lower back"],
    name: "Seated Wide Leg Forward Fold",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "glute medius",
    otherMuscles: ["TFL", "QL"],
    name: "Standing Lateral Hip Reach",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "adductors",
    otherMuscles: ["hip capsule"],
    name: "Half Kneeling Adductor Rock Back",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "TFL",
    otherMuscles: ["lateral hip", "hip flexors"],
    name: "Side Lying TFL Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "wrist flexors",
    otherMuscles: ["finger flexors"],
    name: "Wrist Flexor Stretch Palm Up",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "wrist extensors",
    otherMuscles: ["finger extensors"],
    name: "Wrist Extensor Stretch Palm Down",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "wrist flexors",
    otherMuscles: ["palmar fascia"],
    name: "Prayer Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated or standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "wrist extensors",
    otherMuscles: ["dorsal wrist"],
    name: "Reverse Prayer Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Seated or standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "pronator teres/quadratus",
    otherMuscles: ["wrist flexors"],
    name: "Forearm Pronator Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "supinator",
    otherMuscles: ["biceps", "wrist extensors"],
    name: "Forearm Supinator Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "finger flexors",
    otherMuscles: ["palmar fascia"],
    name: "Finger Extension Table Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "thenar muscles",
    otherMuscles: ["adductor pollicis"],
    name: "Thumb Web Space Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "median nerve interface",
    otherMuscles: ["forearm flexor compartment"],
    name: "Median Nerve Glide",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Seated or standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "radial nerve interface",
    otherMuscles: ["forearm extensors"],
    name: "Radial Nerve Glide",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Seated or standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "gastrocnemius",
    otherMuscles: ["plantar fascia"],
    name: "Wall Gastrocnemius Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "soleus",
    otherMuscles: ["Achilles tendon"],
    name: "Bent Knee Soleus Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "gastrocnemius",
    otherMuscles: ["soleus"],
    name: "Desk Supported Calf Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "soleus",
    otherMuscles: ["ankle capsule"],
    name: "Seated Ankle Dorsiflexion Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "ankle dorsiflexion",
    otherMuscles: ["soleus", "talocrural joint"],
    name: "Knee-to-Wall Ankle Mobility",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "plantar fascia",
    otherMuscles: ["intrinsic foot muscles"],
    name: "Plantar Fascia Ball Roll",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: true,
    equipment: "Ball",
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "tibialis anterior",
    otherMuscles: ["ankle dorsiflexors"],
    name: "Tibialis Anterior Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "peroneals",
    otherMuscles: ["lateral calf"],
    name: "Peroneal Stretch",
    durationSeconds: 30,
    repetitions: 2,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "calves",
    otherMuscles: ["hamstrings", "shoulders"],
    name: "Downward Dog Calf Pedal",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "gastrocnemius/soleus",
    otherMuscles: ["Achilles tendon"],
    name: "Loaded Calf Eccentric Stretch",
    durationSeconds: 45,
    repetitions: 2,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Step",
  },
];

export const STRENGTHEN_LIBRARY: LibraryItem[] = [
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "deep neck flexors",
    otherMuscles: ["suboccipitals"],
    name: "Chin Tuck Repetitions",
    durationSeconds: 30,
    repetitions: 12,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "deep neck flexors",
    otherMuscles: ["cervical stabilisers"],
    name: "Chin Tuck Hold",
    durationSeconds: 30,
    repetitions: 6,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "deep neck flexors",
    otherMuscles: ["cervical extensors"],
    name: "Wall Chin Tuck Press",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "deep neck flexors",
    otherMuscles: ["sternocleidomastoid"],
    name: "Isometric Neck Flexion",
    durationSeconds: 30,
    repetitions: 8,
    skillLevel: "intermediate",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "cervical extensors",
    otherMuscles: ["deep cervical stabilisers"],
    name: "Isometric Neck Extension",
    durationSeconds: 30,
    repetitions: 8,
    skillLevel: "intermediate",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "lateral cervical stabilisers",
    otherMuscles: ["scalenes", "upper trapezius"],
    name: "Isometric Neck Side Bend",
    durationSeconds: 45,
    repetitions: 8,
    skillLevel: "intermediate",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "cervical extensors",
    otherMuscles: ["upper thoracic extensors"],
    name: "Prone Neck Extension Lift",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "deep neck flexors",
    otherMuscles: ["thoracic stabilisers"],
    name: "Quadruped Chin Tuck Hold",
    durationSeconds: 45,
    repetitions: 8,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "deep neck flexors",
    otherMuscles: ["cervical extensors"],
    name: "Band Resisted Cervical Retraction",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "pro",
    context: "Seated",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Cervical Flexor/Extensor Complex",
    primaryMuscle: "deep cervical stabilisers",
    otherMuscles: ["oculomotor-cervical control"],
    name: "Laser Pointer Neck Control Drill",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "pro",
    context: "Seated",
    needsEquipment: true,
    equipment: "Laser pointer/headband",
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "rhomboids",
    otherMuscles: ["middle trapezius"],
    name: "Scapular Retractions",
    durationSeconds: 45,
    repetitions: 15,
    skillLevel: "beginner",
    context: "Seated or standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "middle trapezius",
    otherMuscles: ["rhomboids"],
    name: "Shoulder Blade Squeezes with Hold",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "serratus anterior",
    otherMuscles: ["lower trapezius", "rotator cuff"],
    name: "Wall Slides",
    durationSeconds: 60,
    repetitions: 12,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "lower trapezius",
    otherMuscles: ["rhomboids", "rotator cuff"],
    name: "Wall Angels",
    durationSeconds: 60,
    repetitions: 10,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "middle trapezius",
    otherMuscles: ["rhomboids", "rear deltoid"],
    name: "Band Pull Apart",
    durationSeconds: 45,
    repetitions: 15,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "serratus anterior",
    otherMuscles: ["lower trapezius"],
    name: "Serratus Wall Press",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "lower trapezius",
    otherMuscles: ["rotator cuff"],
    name: "Prone Y Raise",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat or bench",
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "middle trapezius",
    otherMuscles: ["rhomboids", "posterior deltoid"],
    name: "Prone T Raise",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat or bench",
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "serratus anterior",
    otherMuscles: ["pectoral stabilisers"],
    name: "Scapular Push Up Desk",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Axioscapular Group",
    primaryMuscle: "lower trapezius",
    otherMuscles: ["rotator cuff", "rear deltoid"],
    name: "Face Pull with External Rotation",
    durationSeconds: 60,
    repetitions: 12,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "infraspinatus",
    otherMuscles: ["teres minor"],
    name: "Band External Rotation",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "subscapularis",
    otherMuscles: ["pectorals"],
    name: "Band Internal Rotation",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "infraspinatus",
    otherMuscles: ["teres minor", "posterior deltoid"],
    name: "Side Lying External Rotation",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Light dumbbell",
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "rotator cuff",
    otherMuscles: ["lower trapezius"],
    name: "Shoulder W Raises",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "serratus anterior",
    otherMuscles: ["rotator cuff", "pectorals"],
    name: "Desk Push Up Plus",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "rotator cuff",
    otherMuscles: ["serratus anterior", "deltoids"],
    name: "Wall Clock Shoulder Taps",
    durationSeconds: 60,
    repetitions: 10,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "supraspinatus",
    otherMuscles: ["deltoid", "rotator cuff"],
    name: "Scaption Raise",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Light dumbbells optional",
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "infraspinatus",
    otherMuscles: ["teres minor", "lower trapezius"],
    name: "Prone External Rotation at 90 Degrees",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat/bench optional",
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "rotator cuff",
    otherMuscles: ["grip", "scapular stabilisers"],
    name: "Bottoms Up Carry Static",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Kettlebell or dumbbell",
  },
  {
    area: "Scapulohumeral / Rotator Cuff Complex",
    primaryMuscle: "rotator cuff",
    otherMuscles: ["deltoid", "scapular stabilisers"],
    name: "Band Shoulder Stability Circles",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis major",
    otherMuscles: ["triceps", "anterior deltoid"],
    name: "Wall Push Up",
    durationSeconds: 45,
    repetitions: 15,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis major",
    otherMuscles: ["triceps", "serratus anterior"],
    name: "Desk Push Up",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis major",
    otherMuscles: ["anterior deltoid", "triceps"],
    name: "Incline Push Up",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis major",
    otherMuscles: ["triceps", "core"],
    name: "Kneeling Push Up",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "serratus anterior",
    otherMuscles: ["pectoralis major", "triceps"],
    name: "Push Up Plus",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis major",
    otherMuscles: ["anterior deltoid", "triceps"],
    name: "Band Chest Press",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis major",
    otherMuscles: ["serratus anterior"],
    name: "Isometric Palm Press",
    durationSeconds: 30,
    repetitions: 10,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis major",
    otherMuscles: ["anti-rotation core", "serratus anterior"],
    name: "Single Arm Band Press",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis major",
    otherMuscles: ["triceps", "core"],
    name: "Tempo Push Up",
    durationSeconds: 60,
    repetitions: 8,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Pectoral / Anterior Shoulder Complex",
    primaryMuscle: "pectoralis major",
    otherMuscles: ["anterior deltoid"],
    name: "Pec Fly Band Control",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic extensors",
    otherMuscles: ["rib cage mobility"],
    name: "Seated Thoracic Extension Reps",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic extensors",
    otherMuscles: ["lower trapezius"],
    name: "Wall W Raises",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic extensors",
    otherMuscles: ["lower trapezius", "glutes"],
    name: "Prone Cobra",
    durationSeconds: 45,
    repetitions: 8,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic rotators",
    otherMuscles: ["obliques", "scapular stabilisers"],
    name: "Quadruped Thoracic Rotation Reps",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic extensors",
    otherMuscles: ["rhomboids", "middle trapezius"],
    name: "Band Row with Thoracic Extension",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic rotators",
    otherMuscles: ["serratus anterior", "obliques"],
    name: "Wall Windmill Strength Control",
    durationSeconds: 60,
    repetitions: 8,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "rib cage stabilisers",
    otherMuscles: ["serratus anterior", "core"],
    name: "Bear Hover Breathing Hold",
    durationSeconds: 45,
    repetitions: 4,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic extensors",
    otherMuscles: ["diaphragm", "core"],
    name: "Loaded Front Rack Breathing",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Light kettlebell/dumbbell",
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "thoracic extensors",
    otherMuscles: ["rotator cuff", "pecs"],
    name: "Foam Roller Snow Angels",
    durationSeconds: 60,
    repetitions: 10,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Foam roller",
  },
  {
    area: "Thoracic Spine / Rib Cage Complex",
    primaryMuscle: "lower trapezius",
    otherMuscles: ["lats", "rib cage stabilisers"],
    name: "Standing Band Pull Down to Rib Control",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "transversus abdominis",
    otherMuscles: ["diaphragm", "pelvic floor"],
    name: "Seated Brace Breathing",
    durationSeconds: 45,
    repetitions: 8,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "transversus abdominis",
    otherMuscles: ["hip flexors", "obliques"],
    name: "Dead Bug",
    durationSeconds: 60,
    repetitions: 10,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "lower abdominals",
    otherMuscles: ["transversus abdominis"],
    name: "Heel Taps",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "multifidus",
    otherMuscles: ["glutes", "deep core"],
    name: "Bird Dog",
    durationSeconds: 60,
    repetitions: 10,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "obliques",
    otherMuscles: ["glute medius", "QL"],
    name: "Side Plank Modified",
    durationSeconds: 45,
    repetitions: 5,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "obliques",
    otherMuscles: ["transversus abdominis", "glutes"],
    name: "Pallof Press",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "anterior core",
    otherMuscles: ["shoulders", "glutes"],
    name: "Desk Plank",
    durationSeconds: 45,
    repetitions: 3,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "anterior core",
    otherMuscles: ["glutes", "shoulders"],
    name: "Front Plank",
    durationSeconds: 45,
    repetitions: 3,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "anterior core",
    otherMuscles: ["hip flexors"],
    name: "Hollow Body Hold Modified",
    durationSeconds: 45,
    repetitions: 4,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbopelvic Core Stabiliser Complex",
    primaryMuscle: "lateral core",
    otherMuscles: ["grip", "glute medius"],
    name: "Suitcase Carry",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Dumbbell/kettlebell",
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "lumbar stabilisers",
    otherMuscles: ["glutes", "hamstrings"],
    name: "Hip Hinge Drill",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "multifidus",
    otherMuscles: ["glutes", "deep core"],
    name: "Bird Dog Hold",
    durationSeconds: 60,
    repetitions: 8,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "glute max",
    otherMuscles: ["lumbar stabilisers", "hamstrings"],
    name: "Glute Bridge",
    durationSeconds: 45,
    repetitions: 15,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "lumbar extensors",
    otherMuscles: ["glutes", "thoracic extensors"],
    name: "Back Extension Isometric Prone",
    durationSeconds: 45,
    repetitions: 8,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "posterior chain",
    otherMuscles: ["lumbar stabilisers", "hamstrings"],
    name: "Good Morning Bodyweight",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "posterior chain",
    otherMuscles: ["lumbar stabilisers", "glutes"],
    name: "Romanian Deadlift Light",
    durationSeconds: 60,
    repetitions: 10,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Dumbbells optional",
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "quadratus lumborum",
    otherMuscles: ["obliques", "glute medius"],
    name: "Side Plank QL Focus",
    durationSeconds: 45,
    repetitions: 5,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "quadratus lumborum",
    otherMuscles: ["obliques", "glute medius"],
    name: "Standing Band Anti-Side Bend",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "lumbar extensors",
    otherMuscles: ["glutes", "thoracic extensors"],
    name: "Superman Alternating",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Lumbar Extensor / Quadratus Lumborum Complex",
    primaryMuscle: "lumbar stabilisers",
    otherMuscles: ["hamstrings", "glutes"],
    name: "Wall Hip Hinge Isometric",
    durationSeconds: 45,
    repetitions: 5,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "iliopsoas",
    otherMuscles: ["rectus femoris", "deep core"],
    name: "Seated Marches",
    durationSeconds: 45,
    repetitions: 20,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "iliopsoas",
    otherMuscles: ["deep core", "glute medius"],
    name: "Standing Marches",
    durationSeconds: 45,
    repetitions: 20,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "iliopsoas",
    otherMuscles: ["rectus femoris", "core"],
    name: "Band Resisted March",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "hip flexors",
    otherMuscles: ["transversus abdominis"],
    name: "Dead Bug March",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "hip flexors",
    otherMuscles: ["abdominals"],
    name: "Hanging Knee Raise Regression",
    durationSeconds: 45,
    repetitions: 8,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Pull-up bar",
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "iliopsoas",
    otherMuscles: ["glute medius", "core"],
    name: "Standing Knee Drive Hold",
    durationSeconds: 45,
    repetitions: 8,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "hip flexors",
    otherMuscles: ["anterior core", "shoulders"],
    name: "Mountain Climber Slow",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "rectus femoris",
    otherMuscles: ["iliopsoas", "core"],
    name: "Supine Straight Leg Raise",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "iliopsoas",
    otherMuscles: ["rectus femoris"],
    name: "Cable/Band Hip Flexion",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Hip Flexor Complex",
    primaryMuscle: "iliopsoas",
    otherMuscles: ["deep core", "adductors"],
    name: "Psoas Lift Over Object",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "advanced",
    context: "Seated",
    needsEquipment: true,
    equipment: "Small object",
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "gluteus maximus",
    otherMuscles: ["deep hip rotators"],
    name: "Seated Glute Squeeze",
    durationSeconds: 30,
    repetitions: 15,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "gluteus maximus",
    otherMuscles: ["quadriceps", "core"],
    name: "Sit-to-Stand",
    durationSeconds: 60,
    repetitions: 12,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "gluteus maximus",
    otherMuscles: ["quadriceps", "hamstrings"],
    name: "Chair Squat",
    durationSeconds: 60,
    repetitions: 12,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "gluteus maximus",
    otherMuscles: ["hamstrings", "lumbar stabilisers"],
    name: "Glute Bridge",
    durationSeconds: 45,
    repetitions: 15,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "gluteus maximus",
    otherMuscles: ["hamstrings"],
    name: "Standing Hip Extension",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "gluteus medius",
    otherMuscles: ["deep hip rotators"],
    name: "Clamshell",
    durationSeconds: 45,
    repetitions: 15,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "gluteus medius",
    otherMuscles: ["TFL", "hip rotators"],
    name: "Lateral Band Walk",
    durationSeconds: 60,
    repetitions: 10,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mini band",
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "gluteus maximus",
    otherMuscles: ["hamstrings", "core"],
    name: "Single Leg Glute Bridge",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "deep hip rotators",
    otherMuscles: ["glute medius", "core"],
    name: "Hip Airplane Supported",
    durationSeconds: 60,
    repetitions: 6,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Gluteal / Deep Hip Rotator Complex",
    primaryMuscle: "gluteus maximus",
    otherMuscles: ["quadriceps", "glute medius"],
    name: "Step Up",
    durationSeconds: 60,
    repetitions: 10,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Step",
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["glutes"],
    name: "Heel Dig Isometric",
    durationSeconds: 30,
    repetitions: 8,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["calves"],
    name: "Standing Hamstring Curl",
    durationSeconds: 45,
    repetitions: 15,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["glute max", "core"],
    name: "Glute Bridge Heel Walkout",
    durationSeconds: 60,
    repetitions: 8,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["glutes", "spinal stabilisers"],
    name: "Romanian Deadlift Bodyweight",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["glutes", "foot stabilisers"],
    name: "Single Leg RDL Supported",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["glutes", "calves"],
    name: "Hamstring Slider Curl",
    durationSeconds: 60,
    repetitions: 8,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Towel/sliders",
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["glutes", "calves"],
    name: "Nordic Hamstring Regression",
    durationSeconds: 60,
    repetitions: 5,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Anchor or partner",
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["glutes", "lumbar stabilisers"],
    name: "Good Morning",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["glutes", "core"],
    name: "Kickstand RDL",
    durationSeconds: 45,
    repetitions: 10,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Dumbbells optional",
  },
  {
    area: "Hamstring / Posterior Thigh Complex",
    primaryMuscle: "hamstrings",
    otherMuscles: ["glutes", "core"],
    name: "Stability Ball Hamstring Curl",
    durationSeconds: 60,
    repetitions: 10,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Stability ball",
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "gluteus medius",
    otherMuscles: ["TFL", "glute minimus"],
    name: "Standing Hip Abduction",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "gluteus medius",
    otherMuscles: ["glute minimus", "TFL"],
    name: "Side Lying Hip Abduction",
    durationSeconds: 45,
    repetitions: 15,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "gluteus medius",
    otherMuscles: ["deep hip rotators"],
    name: "Clamshell",
    durationSeconds: 45,
    repetitions: 15,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "gluteus medius",
    otherMuscles: ["glute max", "TFL"],
    name: "Mini Band Lateral Walk",
    durationSeconds: 60,
    repetitions: 10,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mini band",
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "gluteus medius",
    otherMuscles: ["obliques", "QL"],
    name: "Side Plank with Hip Abduction",
    durationSeconds: 45,
    repetitions: 8,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Mat optional",
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "adductors",
    otherMuscles: ["pelvic floor", "deep core"],
    name: "Adductor Ball Squeeze",
    durationSeconds: 30,
    repetitions: 12,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: true,
    equipment: "Ball or cushion",
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "adductors",
    otherMuscles: ["obliques", "hip stabilisers"],
    name: "Copenhagen Plank Regression",
    durationSeconds: 45,
    repetitions: 5,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: true,
    equipment: "Chair/bench",
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "adductors",
    otherMuscles: ["deep core", "hip flexors"],
    name: "Standing Adduction Band Pull",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "adductors",
    otherMuscles: ["glutes", "quadriceps"],
    name: "Lateral Lunge",
    durationSeconds: 60,
    repetitions: 10,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Hip Abductor / Adductor Complex",
    primaryMuscle: "glute medius",
    otherMuscles: ["foot intrinsic", "core"],
    name: "Single Leg Balance Hip Control",
    durationSeconds: 45,
    repetitions: 3,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "wrist extensors",
    otherMuscles: ["grip muscles"],
    name: "Wrist Extension Isometric",
    durationSeconds: 30,
    repetitions: 8,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "wrist flexors",
    otherMuscles: ["finger flexors"],
    name: "Wrist Flexion Isometric",
    durationSeconds: 30,
    repetitions: 8,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "wrist extensors",
    otherMuscles: ["finger extensors"],
    name: "Wrist Extension Curl",
    durationSeconds: 45,
    repetitions: 15,
    skillLevel: "intermediate",
    context: "Seated",
    needsEquipment: true,
    equipment: "Light dumbbell",
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "wrist flexors",
    otherMuscles: ["finger flexors"],
    name: "Wrist Flexion Curl",
    durationSeconds: 45,
    repetitions: 15,
    skillLevel: "intermediate",
    context: "Seated",
    needsEquipment: true,
    equipment: "Light dumbbell",
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "pronators/supinators",
    otherMuscles: ["wrist stabilisers"],
    name: "Pronation Supination Control",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "intermediate",
    context: "Seated",
    needsEquipment: true,
    equipment: "Hammer/light dumbbell",
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "finger extensors",
    otherMuscles: ["intrinsic hand muscles"],
    name: "Finger Extension Band Opens",
    durationSeconds: 30,
    repetitions: 20,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: true,
    equipment: "Rubber band",
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "finger flexors",
    otherMuscles: ["forearm flexors", "intrinsic hand"],
    name: "Grip Squeeze",
    durationSeconds: 30,
    repetitions: 15,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: true,
    equipment: "Stress ball",
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "wrist stabilisers",
    otherMuscles: ["forearm muscles"],
    name: "Radial Ulnar Deviation",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "advanced",
    context: "Seated",
    needsEquipment: true,
    equipment: "Light dumbbell",
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "wrist extensors",
    otherMuscles: ["tendon loading"],
    name: "Eccentric Wrist Extension",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "advanced",
    context: "Seated",
    needsEquipment: true,
    equipment: "Light dumbbell",
  },
  {
    area: "Forearm / Wrist / Hand Complex",
    primaryMuscle: "grip",
    otherMuscles: ["forearms", "shoulder stabilisers"],
    name: "Farmer Carry Light",
    durationSeconds: 60,
    repetitions: 1,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Dumbbells or bags",
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "soleus",
    otherMuscles: ["gastrocnemius"],
    name: "Seated Calf Raises",
    durationSeconds: 45,
    repetitions: 20,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "gastrocnemius",
    otherMuscles: ["soleus", "foot intrinsics"],
    name: "Standing Calf Raises",
    durationSeconds: 45,
    repetitions: 20,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "soleus",
    otherMuscles: ["Achilles tendon"],
    name: "Bent Knee Calf Raises",
    durationSeconds: 45,
    repetitions: 15,
    skillLevel: "intermediate",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "gastrocnemius",
    otherMuscles: ["soleus", "foot stabilisers"],
    name: "Single Leg Calf Raise Supported",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "gastrocnemius/soleus",
    otherMuscles: ["Achilles tendon"],
    name: "Eccentric Calf Lowering",
    durationSeconds: 60,
    repetitions: 10,
    skillLevel: "advanced",
    context: "Standing",
    needsEquipment: true,
    equipment: "Step",
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "tibialis anterior",
    otherMuscles: ["ankle dorsiflexors"],
    name: "Toe Raises Wall Supported",
    durationSeconds: 45,
    repetitions: 15,
    skillLevel: "beginner",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "foot intrinsics",
    otherMuscles: ["arch stabilisers"],
    name: "Short Foot Exercise",
    durationSeconds: 30,
    repetitions: 10,
    skillLevel: "intermediate",
    context: "Seated or standing",
    needsEquipment: false,
    equipment: null,
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "intrinsic foot muscles",
    otherMuscles: ["toe flexors"],
    name: "Towel Scrunches",
    durationSeconds: 45,
    repetitions: 15,
    skillLevel: "beginner",
    context: "Seated",
    needsEquipment: true,
    equipment: "Towel",
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "tibialis posterior/peroneals",
    otherMuscles: ["ankle stabilisers"],
    name: "Ankle Inversion Eversion Band",
    durationSeconds: 45,
    repetitions: 12,
    skillLevel: "advanced",
    context: "Seated",
    needsEquipment: true,
    equipment: "Resistance band",
  },
  {
    area: "Calf / Ankle / Foot Complex",
    primaryMuscle: "calf complex",
    otherMuscles: ["Achilles tendon", "foot intrinsics"],
    name: "Pogo Hops Low Amplitude",
    durationSeconds: 45,
    repetitions: 20,
    skillLevel: "pro",
    context: "Standing",
    needsEquipment: false,
    equipment: null,
  },
];
